---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  annotations:
    # This is a hack for rancher & local storage on kind !
    volume.kubernetes.io/selected-node: dummy-control-plane
  # "quarkus-tekton-cli-project-pvc" => project-dir
  name: "project-dir"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  storageClassName: standard
  volumeMode: "Filesystem"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  annotations:
    # This is a hack for rancher & local storage on kind !
    volume.kubernetes.io/selected-node: dummy-control-plane
  # quarkus-tekton-cli-m2-repo-pvc => maven-repo-dir
  name: "maven-repo-dir"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  storageClassName: standard
  volumeMode: "Filesystem"
